### ISSUE TITLE
non-const lvalue reference to type 'QMap<[2 * ...]>' cannot bind to a temporary of type 'QMap<[2 * ...]>'

### ISSUE THREAD

**Issue by sinosoidal** [cglancy/CuteFire#1]
Hi,

I'm trying to compile your CuteFire lib but I have stumbled on this issue. Can you help me? 

How reliable is your lib for a production environment? I'm recently evaluating Firebase as an alternative to Parse shutdown. 

In file included from ../../CuteFire/src/tokengenerator.cpp:1:
../../CuteFire/src/tokengenerator.h:18:70: error: non-const lvalue reference to type 'QMap<[2 \* ...]>' cannot bind to a temporary of type 'QMap<[2 \* ...]>'
        QByteArray createToken(const QVariantMap &data, QVariantMap &options = QVariantMap());
                                                                     ^         ~~~~~~~~~~~~~
../../CuteFire/src/tokengenerator.h:18:70: note: passing argument to parameter 'options' here
1 error generated.
make[1]: **\* [tokengenerator.o] Error 1

Thanks

**Comment by cglancy** [comment]
This library is not ready for production. I had to abandon it because of other priorities. 

What is your build environment? Qt version?

-Charles

**Comment by sinosoidal** [comment]
Hey,

Thanks for your reply. 

I’m using Qt 5.5 and 5.6

Regards,

Nuno

**Comment by cglancy** [comment]
I have removed the default argument. Please try to compile again.
